NXCT-151: Fix entrypoint to be able to set an instance.clid
nuxeo/docker-nuxeo pull request #25
Opened 2019-01-08 19:15 UTC by bdelbosc

2019-01-08 19:15 UTC, nuxeojenkins commented
[View issue in JIRA](https://jira.nuxeo.com/browse/NXCT-151)

2019-01-08 19:49 UTC, dmetzler requested changes
Please run `update.py` script to update all entrypoint versions based on the template.

2019-01-09 23:59 UTC, dmetzler approved these changes

2019-03-25 06:40 UTC, cyrfer commented
Please show an example using the CLID feature. I can't find docs on what to do with this arg.

2019-03-25 19:25 UTC, merged

2019-04-25 19:24 UTC, dmetzler commented
https://github.com/docker-library/official-images/pull/5807