NXCT-194: small improvements on docker-entrypoint.sh and JAVA_OPTS (JDK 11)
nuxeo/docker-nuxeo pull request #32
Opened 2019-07-04 11:09 UTC by ataillefer

2019-07-04 11:09 UTC, nuxeojenkins commented
[View issue in JIRA](https://jira.nuxeo.com/browse/NXCT-194)

2019-07-05 12:20 UTC, dmetzler requested changes
you also have to udpate `templates/nuxeo.conf` to remove gc option.

Once done, run `update.py` and verify no further change has been made.

2019-07-05 13:27 UTC, ataillefer commented
Updated `templates/nuxeo.conf`.
Was wondering about `staging/nuxeo.conf` but I guess not.
Ran `update.py`, no other change.

2019-07-05 13:52 UTC, dmetzler approved these changes

2019-07-05 14:05 UTC, merged